# Generated by Django 3.1.5 on 2021-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0012_auto_20210115_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='Текст письма', max_length=2000, null=True),
        ),
    ]
