# Generated by Django 3.1.5 on 2021-07-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
