# Generated by Django 3.1.5 on 2021-07-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210709_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cover',
        ),
    ]
