# Generated by Django 3.1.5 on 2021-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0009_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_information',
            name='pasport_info',
            field=models.TextField(blank=True, help_text='Паспортные данные', max_length=50, null=True),
        ),
    ]
