# Generated by Django 3.1.5 on 2021-07-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0010_auto_20210706_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_auto',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
