# Generated by Django 3.1.5 on 2021-07-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0011_person_auto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_auto',
            name='client_email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person_auto',
            name='client_phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person_auto',
            name='car_type',
            field=models.CharField(choices=[('1', 'минивен'), ('2', 'универсал'), ('3', 'минивен'), ('4', 'купе'), ('5', 'внедорожник'), ('6', 'кабриолет'), ('7', 'пикап')], help_text='тип кузова', max_length=30, null=True),
        ),
    ]
