# Generated by Django 3.1.5 on 2021-07-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0012_auto_20210710_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_auto',
            name='gear_case',
            field=models.CharField(choices=[('1', 'автомат'), ('2', 'механика')], default='механика', help_text='коробка передач', max_length=8),
        ),
    ]
