# Generated by Django 3.1.5 on 2021-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0014_auto_20210710_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_auto',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
