# Generated by Django 3.1.5 on 2021-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0015_person_auto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_auto',
            name='color',
            field=models.CharField(choices=[('1', 'черный'), ('2', 'красный'), ('3', 'белый'), ('4', 'синий'), ('5', 'зеленый')], max_length=30, null=True),
        ),
    ]
