# Generated by Django 3.1.5 on 2021-07-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0016_auto_20210710_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_auto',
            name='car_type',
            field=models.CharField(choices=[('1', 'минивен'), ('2', 'универсал'), ('3', 'минивен'), ('4', 'купе'), ('5', 'внедорожник'), ('6', 'кабриолет'), ('7', 'пикап'), ('8', 'седан')], help_text='тип кузова', max_length=30, null=True),
        ),
    ]
