# Generated by Django 3.1.5 on 2021-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0017_auto_20210710_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_auto',
            name='gear',
            field=models.CharField(choices=[('1', 'передний'), ('2', 'задний'), ('3', '4х4'), ('4', 'полный')], default='передний', help_text='Привод', max_length=8, null=True),
        ),
    ]
